### PR TITLE
updated JDK version to JDK17

### PR DESCRIPTION
**Pull request by tanmayr71**
JDK 17 is the LTS version and has good features, so changing the version of the jdk to work with

Please ensure your pull request adheres to the following guidelines:

- **Title**: A brief, descriptive summary of your changes.
- **Description**: Explain the changes you've made and why you've made them.
- **Branch Naming**: Prefix the type of change in the branch name and/or select the option relevant:
  - [ ] `chore/` This change requires a documentation update
  - [ ] Bug fix `bugfix/` (non-breaking change which fixes an issue)
  - [ ] New feature `feature/` (non-breaking change which adds functionality)
  - [ ] Breaking change `fix/` (fix or feature that would cause existing functionality to not work as expected)
- **Related Issue(s)**: Mention any issues that are related to these changes.
- **Testing**: Detail the testing that was done to validate the changes.
- **Checklist**:
  - [ ] I have performed a self-review of my own code.
  - [ ] I have added tests that prove my fix is effective or that my feature works.
- **Screenshots/Output**: Include any relevant screenshots or output demonstrating the changes (if applicable).
- **Additional Notes**: Any further comments or notes for the reviewers.

### CODE REVIEW

**Review by utsav-sharma2020 — COMMENTED** [review]
Looks Good.

**Comment by slachitoff** [comment]
In testing the proposed change (which looks great by the way), I noticed a warning regarding duplicate copies of the `maven-surefire-plugin` in our `pom.xml`.

As part of your update, would you mind also deleting the older version from the file:

```xml
<plugin>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>2.22.1</version>
</plugin>

Thank you!

**Review by slachitoff — COMMENTED** [review]
In testing the proposed change (which looks great by the way), I noticed a warning regarding duplicate copies of the `maven-surefire-plugin` in our `pom.xml`.

As part of your update, would you mind also deleting the older version from the file:

```xml
<plugin>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>2.22.1</version>
</plugin>

Thank you!

**Comment by sash7410** [comment]
> In testing the proposed change (which looks great by the way), I noticed a warning regarding duplicate copies of the `maven-surefire-plugin` in our `pom.xml`.
> 
> As part of your update, would you mind also deleting the older version from the file:
> 
> ```
> <plugin>
>   <artifactId>maven-surefire-plugin</artifactId>
>   <version>2.22.1</version>
> </plugin>
> 
> Thank you!
> ```

I have added this on my PR, could you please check!?

**Comment by tanmayr71** [comment]
After discussion with @Hao-191  on Slack, we are going forward with JDK 17 and that change in pom is being added in a different commit, so we will not merge this PR for now.

**Pull request closed without merging**
